pxe-service=0,"Raspberry Pi Boot"

# Disable DNS server (we only need DHCP/TFTP)  
port=0  
 
# DHCP settings  
dhcp-range=192.168.1.100,192.168.1.200,255.255.255.0,24h  # IP range for Pis  
dhcp-option=3,192.168.1.1  # Gateway (router IP)  
#dhcp-option=6,8.8.8.8,8.8.4.4  # DNS servers  
 
# TFTP settings  
enable-tftp  
tftp-root=/srv/tftpboot  # Directory to store boot files  
dhcp-boot=bootcode.bin  # File Pis will request first  
# tftp-secure  # Restrict TFTP to tftp-root  
 
# Logging (optional but helpful for debugging)  
log-dhcp  
log-facility=/var/log/dnsmasq.log 

# Minions (tonight we steal the moon)
# Gru is number 1
dhcp-host=88:A2:9E:7F:B8:7B,192.168.1.102,minion2-kevin,infinite
dhcp-host=88:A2:9E:7F:B6:4D,192.168.1.103,minion3-stuart,infinite
dhcp-host=88:A2:9E:7F:B8:DE,192.168.1.104,minion4-bob,infinite
dhcp-host=2C:CF:67:D4:4A:A4,192.168.1.105,minion5-dave,infinite
dhcp-host=2C:CF:67:D4:4C:3A,192.168.1.106,minion6-harry,infinite
dhcp-host=88:A2:9E:7F:BA:82,192.168.1.107,minion7-jerry,infinite
dhcp-host=2C:CF:67:D4:37:1A,192.168.1.108,minion8-otto,infinite
dhcp-host=2C:CF:67:D4:4A:83,192.168.1.109,minion9-carl,infinite
dhcp-host=2C:CF:67:D4:4A:CC,192.168.1.110,minion10-phil,infinite
dhcp-host=2C:CF:67:D4:47:A0,192.168.1.111,minion11-mel,infinite
dhcp-host=2C:CF:67:D4:4A:51,192.168.1.112,minion12-ron,infinite
dhcp-host=2C:CF:67:D4:4C:FE,192.168.1.113,minion13-gus,infinite
dhcp-host=2C:CF:67:D4:4B:77,192.168.1.114,minion14-tom,infinite
dhcp-host=88:A2:9E:7F:B9:02,192.168.1.115,minion15-ezekiel,infinite
